### ISSUE TITLE
Expected code release date for python version

### ISSUE THREAD

**Issue by ashawkey** [ChirikjianLab/Marching-Primitives#1]
Hi, thanks for the amazing work!
I wonder if there is an expected date for a python implementation?

**Comment by bmlklwx** [comment]
> 

Thanks for your interest! I am currently working on it. Since I am currently preparing for graduation and job hunting, the python version is expected within about 1 or 2 months. I will try to make it asap, and get you informed.

**Comment by ashawkey** [comment]
Thanks for the reply! Looking forward to that and hope everything goes well with you!

**Comment by bmlklwx** [comment]
> Thanks for the reply! Looking forward to that and hope everything goes well with you!

Sorry for the delay of the Python release, since I am preparing my defense recently. 
I will have it done asap.

**Comment by ashawkey** [comment]
Thanks for the information and it's totally no problem!

**Comment by FisherYuuri** [comment]
Hi, thanks for the amazing work! Can I ask for a python  implementation now?

**Comment by FisherYuuri** [comment]
> Hi, thanks for the amazing work! Can I ask for a python implementation now?

Hi, I have implemented python code for this algorithm. Thanks for your interesting work!
https://github.com/FisherYuuri/Marching-Primitives-Python

**Comment by lulongfei-luffy** [comment]
Great work, I would like to know if the Python version of the code has been completed.
I noticed that @FisherYuuri had implemented a Python version for this algorithm, but the results between Matlab and the python version are different. It seems that the Matlab version has better geometry.

This is matlab output
<img width="413" alt="matlab" src="https://github.com/user-attachments/assets/f56549c9-a31d-4684-a601-e59cb5df9b0f">

and this is python output for the same input
<img width="400" alt="python" src="https://github.com/user-attachments/assets/0026c51c-83c2-49ab-acd7-352270a629bd">
