### ISSUE TITLE
Face orientations of marching-primitives results

### ISSUE THREAD

**Issue by bluestyle97** [ChirikjianLab/Marching-Primitives#2]
Hi, thanks for your interesting work! When I visualize the example meshes produced by marching-primitives in Meshlab, it seems that the face orientations are not correct. For example:

"terataner_balrog_mps.stl":
![image](https://github.com/ChirikjianLab/Marching-Primitives/assets/20635237/761af4cb-8be0-4e87-968b-67069f5f720e)

Do you know what the reason is? How to fix it?

**Comment by bmlklwx** [comment]
Currently, the mesh is generated by a very simple algorithm (which can be found in the source code) just for shape visualization purpose, without face orientation computed. The meshlab guesses the normals. We could add the orientation info later, or for now you can try to render the mesh without normals in meshlab. 

Best Regards,
Weixiao

**Comment by bluestyle97** [comment]
Get it. But I didn't find an option in Meshlab to "render the mesh without normals". How did you visualize the meshes in your paper?

**Comment by bmlklwx** [comment]
> Get it. But I didn't find an option in Meshlab to "render the mesh without normals". How did you visualize the meshes in your paper?

We used open3d or matlab. Both work on default setting without problem.

**Comment by bluestyle97** [comment]
Hi, is there any progress on the Python implementation?

**Comment by bmlklwx** [comment]
> Hi, is there any progress on the Python implementation?

Working on it. I just defended my dissertation recently, and kind of busy. Sorry for the delay.

**Comment by qk98** [comment]
> Get it. But I didn't find an option in Meshlab to "render the mesh without normals". How did you visualize the meshes in your paper?

show "double" face or  "cull " back-face.
![image](https://github.com/ChirikjianLab/Marching-Primitives/assets/3952934/41a7493e-62c9-4bb4-80c9-c7f70afdcb5b)

**Comment by bmlklwx** [comment]
Update: the mesh generator of superquadrics has been fixed. Now the output mesh should be correct.
