### ISSUE TITLE
Missing mesh file - Reading Room

### ISSUE THREAD

**Issue by raghavvs** [ChirikjianLab/Marching-Primitives#3]
In the paper, Figure 7 shows result of indoor scene abstraction - I am trying to use this scene for HRM planner but it is missing from the repo. I am not sure if I have overlooked it. Could you let me know where I could find the mesh?

![Screen Shot 2023-08-02 at 6 37 53 AM](https://github.com/ChirikjianLab/Marching-Primitives/assets/93821405/f1108a64-d46c-47e9-a619-55276cecd0c8)

**Comment by bmlklwx** [comment]
Not included in this repo. The model is on my previous desktop, over 15000km away, out of reach! But no worry. I will let my labmates check for you.

**Comment by bmlklwx** [comment]
@raghavvs I have included the marching-cube mesh and superquadric parameters file in this google drive [link](https://drive.google.com/file/d/13oSTtXaso8VtZI7R1vY0KS_wI423JSLd/view?usp=share_link).

**Comment by raghavvs** [comment]
Appreciate it, thank you!
